CREATE TABLE inf_diario (
    data date,
    cnpj_fundo char(18),
    vl_cota numeric(27),
    pl numeric(17),
    captacao numeric(17),
    resgate numeric(17),
    tipo varchar(15),
    nr_cotst integer,
    vl_total numeric(17)
);

CREATE TABLE cad_fnd (
    cnpj_fundo char(18),
    tipo varchar(15),
    nome varchar(100),
    dt_reg date,
    dt_const date,
    cd_cvm int,
    dt_cancel date,
    sit varchar(23),
    dt_ini_sit date,
    dt_ini_ativ date,
    dt_ini_exerc date,
    dt_fim_exerc date,
    classe varchar(23),
    dt_ini_classe date,
    rentab_fundo varchar(55),
    condom char(1),
    cotas char(1),
    exclusivo char(1),
    trib_lprazo char(1),
    publico_alvo varchar(13),
    entid_invest char(1),
    taxa_perfm numeric(24),
    inf_taxa_perfm varchar(400),
    taxa_adm numeric(24),
    inf_taxa_adm varchar(400),
    diretor varchar(100),
    cnpj_admin char(18),
    admin varchar(100),
    pf_pj_gestor char(2),
    cpf_cnpj_gestor varchar(18),
    gestor varchar(100),
    cnpj_auditor varchar(18),
    auditor varchar(100),
    cnpj_custodiante varchar(18),
    custodiante varchar(100),
    cnpj_controlador varchar(18),
    controlador varchar(100)
);
